### ISSUE TITLE
Improve training script

### ISSUE THREAD

**Issue by titipata** [cstorm125/choco-raisin#1]
Some improvement that can be made in `train_image_classification.ipynb`:

``` py
path = Path('../images/') # correct this to point to correct path

# remove failed images
fns = get_image_files(path)
failed = verify_images(fns)
failed.map(Path.unlink)
```

``` py
interp.plot_top_losses(8, nrows=8) # cause the text overlapped
```

**Comment by cstorm125** [comment]
The path is for when running from colab. I'll add local path.

I've already run the cleaning scripts in the data processing notebook.

**Comment by titipata** [comment]
All good then!! Mark as closed.
